- name: Prerequisites
  hosts: [jumpserver, kube_workers, kube_control_plane]
  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Install command line utilities
      apt:
        name: [wget, curl, vim, openssl, git]
        update_cache: true

    - name: Verify system requirements
      shell:
        cmd: |-
          UNAME=$(uname -mov)
          if [[ $UNAME == *"#1 SMP Debian 6.1."* ]] && [[ $UNAME == *") aarch64 GNU/Linux"* ]]; then
            exit 0
          fi

          exit 420
        executable: /usr/bin/bash
