- name: Prerequisites
  hosts: [jumpserver, kube_workers, kube_control_plane]
  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Capture machine specs
      shell: uname -mov
      register: uname
      changed_when: "uname.rc != 0"

    - name: Verify system requirements
      fail:
        msg: failed
      failed_when: "'#1 SMP Debian 6.1.' not in uname.stdout or ') aarch64 GNU/Linux' not in uname.stdout"
