- name: Generate Client Authentication Configs
  hosts: jump_server
  tasks:
    - name: The kubelet Kubernetes Configuration File
      shell:
        cmd: |-
          kubectl config set-cluster kubernetes-the-hard-way \
            --certificate-authority=ca.crt \
            --embed-certs=true \
            --server=https://server.kubernetes.local:6443 \
            --kubeconfig={{ item }}.kubeconfig

          kubectl config set-credentials system:node:${host} \
            --client-certificate={{ item }}.crt \
            --client-key={{ item }}.key \
            --embed-certs=true \
            --kubeconfig={{ item }}.kubeconfig

          kubectl config set-context default \
            --cluster=kubernetes-the-hard-way \
            --user=system:node:{{ item }} \
            --kubeconfig={{ item }}.kubeconfig

          kubectl config use-context default \
            --kubeconfig={{ item }}.kubeconfig
      with_items: "{{ groups['kube_workers'] }}"

    - name: The kube-proxy Kubernetes Configuration File
      shell:
        cmd: |-
          kubectl config set-cluster kubernetes-the-hard-way \
            --certificate-authority=ca.crt \
            --embed-certs=true \
            --server=https://server.kubernetes.local:6443 \
            --kubeconfig=kube-proxy.kubeconfig

          kubectl config set-credentials system:kube-proxy \
            --client-certificate=kube-proxy.crt \
            --client-key=kube-proxy.key \
            --embed-certs=true \
            --kubeconfig=kube-proxy.kubeconfig

          kubectl config set-context default \
            --cluster=kubernetes-the-hard-way \
            --user=system:kube-proxy \
            --kubeconfig=kube-proxy.kubeconfig

          kubectl config use-context default \
            --kubeconfig=kube-proxy.kubeconfig

    - name: The kube-control-manager Kubernetes Configuration File
      shell:
        cmd: |-
          kubectl config set-cluster kubernetes-the-hard-way \
            --certificate-authority=ca.crt \
            --embed-certs=true \
            --server=https://server.kubernetes.local:6443 \
            --kubeconfig=kube-controller-manager.kubeconfig

          kubectl config set-credentials system:kube-controller-manager \
            --client-certificate=kube-controller-manager.crt \
            --client-key=kube-controller-manager.key \
            --embed-certs=true \
            --kubeconfig=kube-controller-manager.kubeconfig

          kubectl config set-context default \
            --cluster=kubernetes-the-hard-way \
            --user=system:kube-controller-manager \
            --kubeconfig=kube-controller-manager.kubeconfig

          kubectl config use-context default \
            --kubeconfig=kube-controller-manager.kubeconfig

    - name: The kube-scheduler Kubernetes Configuration File
      shell:
        cmd: |-
          kubectl config set-cluster kubernetes-the-hard-way \
            --certificate-authority=ca.crt \
            --embed-certs=true \
            --server=https://server.kubernetes.local:6443 \
            --kubeconfig=kube-scheduler.kubeconfig

          kubectl config set-credentials system:kube-scheduler \
            --client-certificate=kube-scheduler.crt \
            --client-key=kube-scheduler.key \
            --embed-certs=true \
            --kubeconfig=kube-scheduler.kubeconfig

          kubectl config set-context default \
            --cluster=kubernetes-the-hard-way \
            --user=system:kube-scheduler \
            --kubeconfig=kube-scheduler.kubeconfig

          kubectl config use-context default \
            --kubeconfig=kube-scheduler.kubeconfig

    - name: The admin Kubernetes Configuration File
      shell:
        cmd: |-
          kubectl config set-cluster kubernetes-the-hard-way \
            --certificate-authority=ca.crt \
            --embed-certs=true \
            --server=https://127.0.0.1:6443 \
            --kubeconfig=admin.kubeconfig

          kubectl config set-credentials admin \
            --client-certificate=admin.crt \
            --client-key=admin.key \
            --embed-certs=true \
            --kubeconfig=admin.kubeconfig

          kubectl config set-context default \
            --cluster=kubernetes-the-hard-way \
            --user=admin \
            --kubeconfig=admin.kubeconfig

          kubectl config use-context default \
            --kubeconfig=admin.kubeconfig

- name: Distribute the Kubernetes Configuration Files
  hosts: jump_server
  tasks:
    - name: Copy the kubelet and kube-proxy kubeconfig files to the worker instances
      shell:
        cmd: |-
          ssh root@{{ item }} "mkdir /var/lib/{kube-proxy,kubelet}"
          
          scp kube-proxy.kubeconfig \
            root@{{ item }}:/var/lib/kube-proxy/kubeconfig \
          
          scp {{ item }}.kubeconfig \
            root@{{ item }}:/var/lib/kubelet/kubeconfig
      with_items: "{{ groups['kube_workers'] }}"

    - name: Copy the kube-controller-manager and kube-scheduler kubeconfig files to the controller instance 
      shell:
        cmd: |-
          scp admin.kubeconfig \
            kube-controller-manager.kubeconfig \
            kube-scheduler.kubeconfig \
            root@{{ item }}:~/
      with_items: "{{ groups['kube_control_plane'] }}"
